export const FETCH_NOTES_START = 'FETCH_NOTES_START';
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';
export const FETCH_NOTES_FAIL = 'FETCH_NOTES_FAIL';

export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';

export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';

export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';

export const CHANGE_FILTER = 'CHANGE_FILTER';
